# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
conda:
  environment: environment.yml
build:
  os: ubuntu-22.04
  tools:
    python: mambaforge-4.10
  jobs:
    pre_create_environment:
      - curl -fsSL https://pixi.sh/install.sh | bash
      - pixi project export conda-environment -e dev environment.yml

mkdocs:
  configuration: mkdocs.yaml
