# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: clio
site_url: https://clio.readthedocs.io/
repo_name: clio
repo_url: https://github.com/calliope-project/clio/
edit_uri: edit/main/docs/
theme:
  name: material
  features:
  - navigation.footer
  - navigation.instant
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.indexes
  - search.suggest
  - search.highlight
  - toc.follow
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      primary: red
      accent: pink
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: red
      accent: pink
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: red
      accent: pink
markdown_extensions:
  - admonition
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.snippets:
      check_paths: true
      restrict_base_path: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom
  - toc:
      anchorlink: true
plugins:
  - git-committers:
      enabled: true
      repository: calliope-project/clio
      branch: main
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_bases: true
            filters:
              - "!^_"
            heading_level: 2
            show_root_heading: true
            merge_init_into_class: true
            show_if_no_docstring: true
            signature_crossrefs: true
            show_root_toc_entry: true
            show_signature_annotations: true
            inherited_members: false
            show_labels: false
          paths: [src]
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://pandas.pydata.org/docs/objects.inv
            - https://docs.xarray.dev/en/stable/objects.inv

nav:
  - Home: index.md
  - Background:
    - Background/motivation.md
    - Background/our_framework.md
  - Modules: Modules/modules.md
  - Developer guidelines:
    - Developer_guidelines/getting_started.md
    - Developer_guidelines/requirements.md
    - Developer_guidelines/templates.md
  - API clio_tools:
    - clio_tools_API/index.md
    - clio_tools_API/data_modules.md

copyright: Copyright &copy; since 2025 <a href="https://github.com/calliope-project/clio/blob/main/AUTHORS">clio contributors</a> (MIT licensed)
