name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
      - uses: astral-sh/setup-uv@v5
        with:
          uv-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync
      - name: Build package
        run: uv build
      - name: Run tests
        run: uv run pytest
